service: personal-study-guide-backend
frameworkVersion: '4'
useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  # Global CORS configuration for httpApi
  httpApi:
    cors: true
  environment:
    UPLOAD_BUCKET_NAME: ${self:custom.bucketName}
    SUPABASE_URL: ${env:SUPABASE_URL}
    SUPABASE_KEY: ${env:SUPABASE_KEY}
    DEEPSEEK_API_KEY: ${env:DEEPSEEK_API_KEY}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
          Resource: "arn:aws:s3:::${self:custom.bucketName}/*"

custom:
  bucketName: study-guide-uploads-${sls:stage}

# This is required to expose the "offline" command
plugins:
  - serverless-offline

functions:
  getUploadUrl:
    handler: src/handlers/getUploadUrl.handler
    events:
      - httpApi:
          path: /upload-url
          method: post
  
  processPdfEvent:
    handler: src/handlers/processPdf.handler
    events:
      - s3:
          bucket: ${self:custom.bucketName}
          event: s3:ObjectCreated:Put
          rules:
            - suffix: .pdf
          existing: true

  getStudyGuide:
    handler: src/handlers/getStudyGuide.handler
    events:
      - httpApi:
          path: /study-guide/{fileKey}
          method: get